modify html and css files
brightbrain20/code-review pull request #1
Opened 2022-12-13 12:39 UTC by brightbrain20

created a survey form

2022-12-13 13:51 UTC, brightbrain20 reviewed
Hi @brightbrain20, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

![Invalid](https://user-images.githubusercontent.com/20554583/205453857-4dbf06ea-07e2-4c5f-b8d3-7be5ad23a926.gif)

You have submitted a project that has failing linter checks. Kindly fix the linter errors.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-13 14:09 UTC, Favourezeugwa requested changes
## STATUS: REQUIRES CHANGES 🚦 ⚠️ ♻️ 

Hi @brightbrain20  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-brianna](https://user-images.githubusercontent.com/99246359/201470450-173d4ea7-fe78-470e-a872-142a58b56294.gif)


## Highlights 💯 
- GitHub's review feature used ✔️
- Gif used ✔️
- Stated reason WHY code was Invalidated✔️


## Required Changes ♻️

- Hi @brightbrain20 , Great Job using GitHub's review feature to Invalidate your code because of Linter errors. 👍🏽 

- But the  goal of this project is to learn how to use GitHub features for reviews and how to communicate professionally. 🥂 

- I'd like to kindly suggest that you use inline comments give at least two review comments in piece of codes you think are not properly written. This comments should be as polite as possible.
[Here is a link on how to use inline comments](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request). You should focus on the `Starting a review` from bullet point 3. 🤗 

- You should perform a code review on this PR and check to see if you have applied HTML & CSS best practices introduced by the [How to give a code review?](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md)  🥂 

- At this point, you can pardon the linters, even if they are failing. Code reviewers will review your review comments and not your code. 🌸

⚠️ Kindly remember to 'Edit' your entire summary from "Invalid review request" to "Required Changes".

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-14 10:42 UTC, brightbrain20 reviewed
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! I will suggest you to make the following changes.

Required Changes ♻️
📌 correct Linters error 
📌 Give a Descriptive pull request
📌 Have a Professional README file

2022-12-14 10:42 UTC, brightbrain20 commented on styles.css
> +    border: 0;
Good job implementing the border but i will highly suggest that you remove one border from the element because it will lead to linters error.

2022-12-14 10:55 UTC, leonardodiasb approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @brightbrain20 🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

## Highlights

 - Professional message. ✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-14 11:04 UTC, merged